image: python:3.8.2

definitions:
  steps:
    - step: &build
        name: Build
        image: node:14.17
        caches:
          - node
        script:
          - node --version
          - npm --version
          - npm cache clean --force
          - npm install -g typescript
          - npm install
          - npm run build

  deploy-script: &deploy
    caches:
      - pip
    script:
      - MESSAGE=`git log --format=%B -n 1 $BITBUCKET_COMMIT` # getting commit message
      - apt update
      - apt install -y rsync
      - pip3 install ansible==2.9.8
      - chmod 700 ci-scripts
      - cd ci-scripts
      # run update playbook
      - ansible-playbook -i "$HOST" -e "ansible_user=$USER \
        SERVER_HOST=$SERVER_HOST \
        SERVER_PORT=$SERVER_PORT \
        SERVICE_NAME=$SERVICE_NAME \
        backend_bin=$backend_bin \
        DATABASE_LINK=$DATABASE_LINK \
        DOMAIN_NAME=$DOMAIN_NAME \
        FILE_SERVICE_URL=$FILE_SERVICE_URL \
        CORS_ORIGINS=$CORS_ORIGINS \
        CORS_METHODS=$CORS_METHODS \
        AUTH_JWT_FILESERVICE_SECRET=$AUTH_JWT_FILESERVICE_SECRET \
        AUTH_JWT_FILESERVICELINK_SECRET=$AUTH_JWT_FILESERVICELINK_SECRET \
        NODE_ENV=$NODE_ENV \
        SRC_DIR=$BITBUCKET_CLONE_DIR/" backend-update.yml;

pipelines:
  branches:
    master:
      - step:
          <<: *build
      - step:
          name: Deploy
          deployment: Production
          <<: *deploy

    staging:
      - step:
          <<: *build
      - step:
          name: Deploy
          deployment: Staging
          <<: *deploy

    develop:
      - step:
          <<: *build
      - step:
          name: Deploy
          deployment: Develop
          <<: *deploy