definitions:
  types.IFileResponse:
    properties:
      ext:
        type: string
      hash:
        type: string
      id:
        type: string
      mime:
        type: string
      name:
        type: string
      public:
        type: boolean
      userId:
        type: string
    type: object
  types.IOutputError:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
      ok:
        type: boolean
    type: object
  types.IOutputOk:
    properties:
      ok:
        type: boolean
      result: {}
    type: object
  types.IOutputPagination:
    properties:
      ok:
        type: boolean
      result:
        $ref: '#/definitions/types.IOutputPaginationResult'
    type: object
  types.IOutputPaginationResult:
    properties:
      count:
        type: integer
      rows:
        items: {}
        type: array
    type: object
info:
  contact: {}
paths:
  /files:
    get:
      description: List of files
      parameters:
      - description: limit result in response
        in: query
        name: limit
        type: integer
      - description: offset result in response
        in: query
        name: offset
        type: integer
      - description: search text
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.IOutputPagination'
            - properties:
                result:
                  allOf:
                  - $ref: '#/definitions/types.IOutputPaginationResult'
                  - properties:
                      rows:
                        items:
                          $ref: '#/definitions/types.IFileResponse'
                        type: array
                    type: object
              type: object
      summary: List of files
      tags:
      - files
    post:
      consumes:
      - multipart/form-data
      description: create file
      parameters:
      - description: Public file
        in: body
        name: public
        schema:
          type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.IOutputOk'
            - properties:
                result:
                  $ref: '#/definitions/types.IFileResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/types.IOutputError'
      summary: Create file
      tags:
      - files
swagger: "2.0"
